// Generated by CoffeeScript 1.8.0
var axes, gotData, myAxes, myTernary, plot, svg;

svg = d3.select('body').append('svg').attr({
  width: 500,
  height: 500
});

axes = svg.append('g').attr('id', 'axes');

plot = svg.append('g').attr('id', 'plot');

myTernary = ternaryPlot().range([0, 400]);

myAxes = ternaryAxes(myTernary);

gotData = function(d) {
  var f, type;
  for (type in d) {
    f = function() {
      return type;
    };
    plot.append('path').attr({
      d: function() {
        return myTernary.line(d[type], function(d) {
          return [d.sand, d.silt, d.clay];
        }) + 'Z';
      },
      'class': 'ternary-line',
      'id': type.replace(' ', '-')
    }).on('click', function(d) {
      console.log(this.id);
    });
  }
};

myAxes.ticks().minorTicks([d3.range(0, 101, 5)]).draw('#axes');

d3.json('data.json', gotData);
