// Generated by CoffeeScript 1.8.0
(function() {
  var angles, line, path, randomid;

  path = void 0;

  d3.ternary = {};

  randomid = function() {
    var i, pos, possible, text, _i;
    text = "";
    possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz";
    for (i = _i = 0; _i <= 3; i = ++_i) {
      pos = Math.floor(Math.random() * possible.length);
      text += possible.charAt(pos);
    }
    return text;
  };

  line = function(interpolator) {
    if (!interpolator) {
      interpolator = 'linear';
    }
    return path = d3.svg.line().x(function(d) {
      return d[0];
    }).y(function(d) {
      return d[1];
    }).interpolate(interpolator);
  };

  angles = [0, 120, 240];

  d3.ternary.graticule = function() {
    var gratAxis, graticule, majorInterval, majorTicks, minorInterval, minorTicks;
    majorInterval = 0.1;
    minorInterval = null;
    majorTicks = function() {
      var int, start, ticks;
      ticks = [];
      int = majorInterval;
      start = int;
      while (start < 1) {
        ticks.push(start);
        start += int;
      }
      return ticks;
    };
    minorTicks = function() {
      var start, ticks;
      ticks = [];
      if (minorInterval == null) {
        return ticks;
      }
      start = minorInterval;
      while (start < 1) {
        if (start % majorInterval !== 0) {
          ticks.push(start);
        }
        start += minorInterval;
      }
      return ticks;
    };
    gratAxis = d3.svg.axis().tickValues(majorTicks());
    graticule = function(plot) {
      var axisGraticule;
      axisGraticule = function(axis, i) {
        var container, draw, selA, selB;
        container = d3.select(this);
        selA = container.selectAll("path.minor").data(minorTicks());
        selA.enter().append("path").attr({
          "class": "minor"
        });
        selB = container.selectAll("path.major").data(majorTicks());
        selB.enter().append("path").attr({
          "class": "major"
        });
        draw = function() {
          gratAxis.scale(plot.scale);
          selA.attr({
            d: plot.rule(i)
          });
          return selB.attr({
            d: plot.rule(i)
          });
        };
        plot.on("resize." + (randomid()), draw);
        return draw();
      };
      return plot.axes().selectAll(".graticule").data([gratAxis, gratAxis, gratAxis]).enter().append("g").attr({
        "class": "graticule"
      }).each(axisGraticule);
    };
    graticule.axis = function() {
      return gratAxis;
    };
    graticule.majorInterval = function(d) {
      if (!d) {
        return majorInterval;
      }
      majorInterval = d;
      return graticule;
    };
    graticule.minorInterval = function(d) {
      if (!d) {
        return minorInterval;
      }
      minorInterval = d;
      return graticule;
    };
    return graticule;
  };

  d3.ternary.scalebars = function() {
    var adjustText, baryAxis, scalebar;
    baryAxis = d3.svg.axis().tickSize(10).tickFormat(d3.format("%")).tickValues([.2, .4, .6, .8]).orient("top");
    adjustText = function(d, i) {
      if (i !== 1) {
        return;
      }
      return d3.select(this).selectAll("text").attr({
        transform: function(d) {
          var y;
          y = d3.select(this).attr("y");
          return "translate(0 " + (-y) + ") rotate(-180 0 " + (2 * y) + ")";
        }
      });
    };
    scalebar = function(plot) {
      var b_axes, draw;
      b_axes = plot.axes().selectAll(".bary-axis").data(angles).enter().append("g").attr({
        "class": "bary-axis"
      });
      draw = function() {
        var offs, r;
        baryAxis.scale(plot.scale);
        r = plot.radius();
        offs = plot.center();
        return b_axes.call(baryAxis).attr({
          transform: function(d, i) {
            var x, y;
            x = offs[0];
            y = offs[1];
            return "rotate(" + (60 + i * 120) + " " + x + " " + y + ") translate(0 " + (r / 2) + ")";
          }
        }).each(adjustText);
      };
      plot.on("resize." + (randomid()), draw);
      return draw();
    };
    return scalebar;
  };

  d3.ternary.vertexLabels = function(labels) {
    var L, pad, rotate, sel;
    sel = null;
    rotate = [0, 60, -60];
    pad = 20;
    L = function(plot) {
      var data, draw;
      data = labels.map(function(l, i) {
        return {
          label: l,
          angle: angles[i]
        };
      });
      sel = plot.axes().selectAll(".vertex-label").data(data);
      sel.enter().append("text").text(function(d) {
        return d.label;
      }).attr({
        dy: ".35em",
        "text-anchor": "middle",
        "class": "vertex-label"
      });
      draw = function() {
        var offs, radius;
        offs = plot.center();
        radius = plot.radius();
        return sel.attr({
          transform: function(d, i) {
            var a, x, y;
            a = -d.angle * Math.PI / 180;
            x = offs[0] + Math.sin(a) * (radius + pad);
            y = offs[1] - Math.cos(a) * (radius + pad);
            return "translate(" + x + "," + y + ")rotate(" + rotate[i] + ")";
          }
        });
      };
      plot.on("resize." + (randomid()), draw);
      draw();
      return sel;
    };
    return L;
  };

  d3.ternary.neatline = function() {
    var createPoint, neatline;
    createPoint = function(i) {
      var a;
      a = [0, 0, 0];
      a[i] = 1;
      return a;
    };
    neatline = function(plot) {
      var draw, el, i;
      el = plot.node().append("polygon");
      el.datum((function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; _i <= 2; i = ++_i) {
          _results.push(createPoint(i));
        }
        return _results;
      })()).attr({
        "class": "neatline"
      });
      draw = function() {
        return el.attr({
          points: function(d) {
            var di;
            di = d.map(function(c) {
              i = plot.point(c);
              return i.join(",");
            });
            return di.join(" ");
          }
        });
      };
      plot.on("resize." + (randomid()), draw);
      return draw();
    };
    return neatline;
  };

  d3.ternary.plot = function() {
    var T, axes, callOnCreate, events, height, innerHeight, innerWidth, margin, outerHeight, outerWidth, plot, radius, rescaleView, scale, svg, width;
    outerWidth = 500;
    outerHeight = 500;
    margin = {
      top: 50,
      bottom: 50,
      left: 50,
      right: 50
    };
    radius = null;
    height = null;
    width = null;
    svg = null;
    axes = null;
    plot = null;
    callOnCreate = [];
    scale = d3.scale.linear().domain([0, 1]).range([0, 1]);
    events = d3.dispatch("resize");
    innerWidth = function(w) {
      return w - margin.left - margin.right;
    };
    innerHeight = function(h) {
      return h - margin.top - margin.bottom;
    };
    rescaleView = function() {
      var center;
      if (width == null) {
        width = innerWidth(outerWidth);
      }
      if (height == null) {
        height = innerHeight(outerHeight);
      }
      if (radius == null) {
        radius = width / Math.sqrt(3);
      }
      center = [width / 2, radius];
      if (svg == null) {
        return;
      }
      svg.attr({
        transform: "translate(" + margin.left + "," + margin.top + ")",
        width: width,
        height: height
      });
      d3.select(svg.node().parentElement).attr({
        width: outerWidth,
        height: outerHeight
      });
      scale.range([0, width]);
      return events.resize();
    };
    T = function(el) {
      var svg_;
      svg_ = el.selectAll("svg").data([null]);
      svg = svg_.enter().append("svg").append("g");
      axes = svg.append('g').attr('id', 'axes');
      plot = svg.append('g').attr('id', 'plot');
      rescaleView();
      callOnCreate.forEach(function(f) {
        return f(T);
      });
      return callOnCreate = [];
    };
    T.on = function(n, f) {
      return events.on(n, f);
    };
    T.fit = function(w, h) {
      var nh, nw, r;
      if (arguments.length === 2) {
        nw = innerWidth(w);
        nh = innerHeight(h);
        if (nh <= Math.sqrt(3) / 2 * nw) {
          r = nh * 2 / 3;
        } else {
          r = nw / Math.sqrt(3);
        }
      } else {
        r = nw / Math.sqrt(3);
      }
      T.radius(r);
      return T;
    };
    T.node = function() {
      return svg;
    };
    T.axes = function() {
      return axes;
    };
    T.plot = function() {
      return plot;
    };
    T.call = function(f) {
      if (svg != null) {
        f(T);
      } else {
        callOnCreate.push(f);
      }
      return T;
    };
    T.scale = scale;
    T.margin = function(m) {
      if (m == null) {
        return margin;
      }
      margin = m;
      return T;
    };
    T.point = function(coords) {
      var normalized, pos, sum;
      pos = [0, 0];
      sum = d3.sum(coords);
      if (sum !== 0) {
        normalized = coords.map(function(d) {
          return d / sum;
        });
        pos[0] = scale(normalized[1] + normalized[0] / 2);
        pos[1] = scale(Math.sqrt(3) / 2 * (normalized[2] + normalized[1]));
      }
      return pos;
    };
    T.path = (function(_this) {
      return function(coordsList, accessor, interpolator) {
        var positions;
        line(interpolator);
        if (!accessor) {
          accessor = function(d) {
            return d;
          };
        }
        positions = coordsList.map(function(d) {
          return T.point(accessor(d));
        });
        return path(positions) + "Z";
      };
    })(this);
    T.rule = function(axis) {
      return function(value) {
        var ends;
        ends = [];
        if (axis === 0) {
          ends = [[0, 1 - value, value], [1 - value, 0, value]];
        } else if (axis === 1) {
          ends = [[0, value, 1 - value], [1 - value, value, 0]];
        } else if (axis === 2) {
          ends = [[value, 0, 1 - value], [value, 1 - value, 0]];
        }
        return T.path(ends);
      };
    };
    T.getValues = function(pos) {
      var a, b, c;
      pos = pos.map(scale.inverse);
      c = 1 - pos[1];
      b = pos[0] - c / 2;
      a = y - b;
      return [a, b, c];
    };
    T.range = function(range) {
      return T;
    };
    T.radius = function(r) {
      if (r != null) {
        radius = r;
        height = r * 3 / 2;
        width = r * Math.sqrt(3);
        outerHeight = height + margin.top + margin.bottom;
        outerWidth = width + margin.left + margin.right;
        rescaleView();
      } else {
        return radius;
      }
      return T;
    };
    T.center = function() {
      return [width / 2, radius];
    };
    return T;
  };

}).call(this);
